version: 2.0
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout:   
      - run:gradle test
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'