version: 2.0
jobs:
  build:
    docker:
        - image: circleci/openjdk:8-jdk
    steps:
        - checkout   
        - run:
            command: gradle test
        - store_test_results:
            path: .